apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apim-frontend
  description: "Public frontend for the HMCTS API Marketplace"
  annotations:
    jenkins.io/job-full-name: "cft:HMCTS_d_to_i/frontend-api-marketplace"
    github.com/project-slug: 'hmcts/frontend-api-marketplace'
  tags:
    - nodejs
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=api-marketplace-tech
      title: "#api-marketplace-tech on Slack"
      icon: chat
spec:
  type: service
  system: apim
  lifecycle: experimental
  owner: group:dts-api-marketplace
